### ISSUE TITLE
failed to delete vrf

### ISSUE THREAD

**Issue by dsx1123** [CiscoDevNet/terraform-provider-dcnm#3] opened 2021-02-09 19:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### DCNM version

* V 11.5.1

### Affected Resource(s)

* dcnm_vrf

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_providers {
    dcnm = {
      source = "CiscoDevNet/dcnm"
      version = "0.0.1"
    }
  }
}
provider "dcnm" {
  username = "admin"
  password = "xxx"
  url      = "https://10.20.2.63"
  # expiry   = 900000
}

data "dcnm_inventory" "leaf1" {
  fabric_name = "fabric-dmz"
  switch_name = "C9316D-GX-L01"
}

data "dcnm_inventory" "leaf2" {
  fabric_name = "fabric-dmz"
  switch_name = "C9316D-GX-L02"
}

resource "dcnm_vrf" "vrf-blue" {
  fabric_name             = "fabric-dmz"
  name                    = "BLUE"
  #vlan_id                 = 2002
  vlan_name               = "BLUE"
  description             = "vrf created from terraform"
  intf_description        = "vrf blue"
  #tag                     = "1250"
  max_bgp_path            = 2
  max_ibgp_path           = 4
  trm_enable              = false
  rp_external_flag        = false
  rp_address              = "1.2.3.4"
  loopback_id             = 15
  mutlicast_address       = "10.0.0.2"
  mutlicast_group         = "224.0.0.1/4"
  ipv6_link_local_flag    = "true"
  trm_bgw_msite_flag      = false
  advertise_host_route    = false
  advertise_default_route = "true"
  static_default_route    = false
  deploy                  = true
  attachments {
    serial_number = "${data.dcnm_inventory.leaf1.serial_number}"
    #vlan_id       = 2300
    attach        = true
  }
  attachments {
    serial_number = "${data.dcnm_inventory.leaf2.serial_number}"
    #vlan_id       = 2300
    attach        = true
  }
}

#resource "dcnm_vrf" "vrf-red" {
  #fabric_name             = "fabric-dmz"
  #name                    = "red"
  #deploy                  = true
  #attachments {
    #serial_number = "${data.dcnm_inventory.leaf1.serial_number}"
    #attach        = true
  #}
  #attachments {
    #serial_number = "${data.dcnm_inventory.leaf2.serial_number}"
    #attach        = true
  #}
#}
```

### Debug Output

[debug output](https://gist.github.com/dsx1123/063c640df2be314747dfb58e2f1d0048)
### Expected Behavior

vrf red should be removed from dcnm

### Actual Behavior

vrf red is only  detached from leaf switches but not actually removed

### Steps to Reproduce

1. uncomment below part from above plan:
```hcl
#resource "dcnm_vrf" "vrf-red" {
  #fabric_name             = "fabric-dmz"
  #name                    = "red"
  #deploy                  = true
  #attachments {
    #serial_number = "${data.dcnm_inventory.leaf1.serial_number}"
    #attach        = true
  #}
  #attachments {
    #serial_number = "${data.dcnm_inventory.leaf2.serial_number}"
    #attach        = true
  #}
#}
```
3.  `terraform apply` to create the resource
4. then comment out the resource vrf-red and apply it again

### References

* #0000

**Comment by nkatarmal-crest** [comment] 2021-02-10 12:38
This is duplicate of #6. @dsx1123 can we close this?

**Closed** 2021-02-18 16:16 UTC
Labels: duplicate
